pipeline {
    agent any 

    environment {
        AWS_REGION = "ap-south-1"
        AWS_CREDENTIALS = credentials('aws-terraform-creds')
    }

    stages {
        stage("Check Terraform Version") {
            steps {
                sh "terraform --version"
            }
        }

        stage("Terraform init") {
            steps {
                dir('01-VPC') {
                    sh 'terraform init'
                }
            }
        }
    }
}