pipeline {
    agent any 

    environment {
        AWS_REGION = "ap-south-1"
        AWS_CREDENTIALS = credentials('aws-terraform-creds')
    }

    stages {
        stage("Check Terraform Version") {
            steps {
                sh "terraform --version"
            }
        }

        stage("Terraform init") {
            steps {
                dir('01-VPC') {
                    sh 'terraform init'
                }
            }
        }

        stage("Terraform Validate") {
            steps {
                dir('01-VPC') {
                    sh 'terraform validate'
                }
            }
        }

        stage("Terraform Plan") {
            steps {
                dir('01-VPC') {
                    sh 'terraform plan -out=plan.out'
                }
            }
        }

        stage("Terraform Apply") {
            input {
                message "Review the Terraform Plan. Do you want to apply the changes?"
                ok "Yes, Apply changes"
                submitter "admin"
            }
            steps {
                dir('01-VPC') {
                    sh 'terraform apply -auto-approve plan.out'
                }
            }
        }

        // You can comment this step as im only doing this to destroy the created resources
        stage("Terraform Destroy") {
            input {
                message "Review the Terraform Plan. Do you want to destroy the changes?"
                ok "Yes, Destroy changes"
                submitter "admin"
            }
            steps {
                dir('01-VPC') {
                    sh 'terraform destroy -auto-approve'
                }
            }
        }
    }
}